### ISSUE TITLE
BeerJs in Faenza (Italy)

### ISSUE THREAD

**Issue by b4dnewz** [beerjs/meta#108]
![faenza](http://www.cittadarte.emilia-romagna.it/images/destinazioni/faenza-piazza-del-popolo-paolo-barone.jpg)

### BeerJs Faenza

Hi everybody, I've just seen this idea and I would like to participate by adding/organizing a BeerJs event in my city, [Faenza](https://www.google.it/maps?q=faenza&um=1&ie=UTF-8&sa=X&ved=0ahUKEwizwP3tsZrVAhXBaVAKHd05Ag0Q_AUICygC). 🍺 

It's a small italian city but is rich of coding maniacs and it will be awesome to group them.

> Faenza is noted for its manufacture of majolica-ware glazed earthenware pottery, known from the name of the town as faience.

PS: It's also known for having more bars than people lol

Preferred name for the repo: `beerjs/faenza`

Only organizer (for now) @b4dnewz

**Comment by jordanpapaleo** [comment]
Sounds Great!

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/faenza

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks,

Jordan

**Comment by b4dnewz** [comment]
awesome!

**Comment by b4dnewz** [comment]
@jordanpapaleo can you give me the access to faenza repository as owner or as a role that I can edit the repository settings? I would like to enable the https github pages for the repo.
Thanks in advance!

**Comment by jordanpapaleo** [comment]
I gave your team, which is only you, admin access to your repo.  Be careful ;)
