### ISSUE TITLE
Repo for Lausanne, Switzerland

### ISSUE THREAD

**Issue by j-nolan** [beerjs/meta#109]
Hello!

I'm planning on importing BeerJS to beautiful Lausanne, Switzerland. Could you help me make this happen?

Thanks!

Repo name: beerjs/lausanne
Admin: @j-nolan

**Comment by maasencioh** [comment]
do you have a place? that sounds great!

**Comment by j-nolan** [comment]
Not yet. My plan is to announce and promote the first event in a general area (Lausanne city center), see how many people show their interest. This should give me an estimate of the size of the place we'd need.

I would then contact local bars and restaurants to see which one could accommodate us.

I already have a few ideas, like the Qwertz Café that already hosted the local frontend meetup.

By the way I see that you are/were in Lausanne. If you'd like to co-organize or know someone that would, let me know!

**Comment by lpatiny** [comment]
We could probably host you in Hackuarium http://www.hackuarium.ch/en/ and I'm also interested in this meeting. We are working on many open-source projects:
* http://github.com/mljs
* http://github.com/image-js
* http://github.com/cheminfo-js

**Comment by j-nolan** [comment]
Nice! I heard about Hackuarium through Sacha (Fixme). Would be cool to meet you guys. Excited to see there are already potential places and interest for a BeerJS in Lausanne!

**Comment by lpatiny** [comment]
I will be around tomorrow evening around 7PM. You may always contact me on telegram http://t.me/lpatiny

**Comment by jordanpapaleo** [comment]
I'll get you setup soon :)

Sent from my smallest computer

On Jul 25, 2017, at 7:17 AM, Luc Patiny <notifications@github.com> wrote:

I will be around tomorrow evening around 7PM. You may always contact me on telegram http://t.me/lpatiny

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/lausanne

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Sorry I took so long and thanks,

Jordan
