### ISSUE TITLE
Add new admin to Aarhus

### ISSUE THREAD

**Issue by slonoed** [beerjs/meta#119]
Hi!

@orbiteleven asks for admin access for both of us:
https://github.com/beerjs/meta/issues/117
However, I don't have access. Could you add me to https://github.com/beerjs/aarhus

Thanks!

**Comment by orbiteleven** [comment]
Looks like neither of us have admin access. I'd gotten it for https://github.com/beerjs/abq, so I assume that's a mistake?

**Comment by jordanpapaleo** [comment]
Hi Guys

Been crushed lately at work. I'll try to get everything resolved tomorrow. 

Sent from my smallest computer

On Sep 25, 2017, at 3:19 PM, Damon <notifications@github.com> wrote:

Looks like neither of us have admin access. I'd gotten it for https://github.com/beerjs/abq, so I assume that's a mistake?

**Comment by jordanpapaleo** [comment]
Just sent you the invite.  Damon already has access.

By default we just give teams write access to the repo.  Team Aarhus has that.

![image](https://user-images.githubusercontent.com/1728807/31133910-9cadbcb6-a815-11e7-8681-233e9c079c9c.png)

Are you specifically requesting admin access for your team?

**Comment by slonoed** [comment]
@jordanpapaleo no, write access is ok. Thanks!
