### ISSUE TITLE
Access to beerjs/sp and delete beerjs/saopaulo

### ISSUE THREAD

**Issue by MateusSilveira98** [beerjs/meta#134]
My friend @codermarcos, has a repo, BeerJS / SP. 
I would like to ask access to the this repo. How already exist beerjs/sp. I want help

Repo to access:
beerjs/sp = https://github.com/beerjs/sp

Repo to delete:
beerjs/saopaulo = https://github.com/beerjs/saopaulo

**Comment by MateusSilveira98** [comment]
@jordanpapaleo

**Comment by jordanpapaleo** [comment]
Please have him make the request. Thanks. 

Sent from my smallest computer

On May 14, 2018, at 2:02 PM, Mateus da Silveira Costa <notifications@github.com> wrote:

@jordanpapaleo

**Comment by jordanpapaleo** [comment]
This is complete :)
