### ISSUE TITLE
Chapter in Oslo 

### ISSUE THREAD

**Issue by theneva** [beerjs/meta#136]
# New Chapter Request

What will you repo be named?

Oslo

Who will be your admins?

@theneva, @simenb, @kamperud, @ervikleo

Do you have twitter handles I can include in announcing your new chapter?

@theneva, @simenb

Question: we're part of a company (@finn-no) and would like to start some sort of meetup with sponsored beer, and beerjs seems like a perfect fit for us. We're thinking really low-key non-recruitment-heavy events, but there will obviously be an association with the brand. Are there any restrictions when it comes to this?

Thanks in advance!

**Comment by jordanpapaleo** [comment]
Hi.  Doing this now :)

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/oslo

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1.  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2. Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3. Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4. Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5. Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

6. Feel free to direct message me on twitter  @jordanpapaleo :)


Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
I have not slacked that hard in a while.  Sorry guys.

**Comment by jordanpapaleo** [comment]
Is everything good for you guys

Sent from my smallest computer

On Jun 11, 2018, at 1:24 AM, Martin Lehmann <notifications@github.com> wrote:

@jordanpapaleo sorry to bother you directly, but wondering if this is totally out of the question so we have to look somewhere else :)

**Comment by theneva** [comment]
Hey, yes, perfect, thanks a lot! Will get around to actually doing some stuff sometime this week :D
