### ISSUE TITLE
BeerJs on Bagé, Rio Grande do Sul, Brasil

### ISSUE THREAD

**Issue by irioborges** [beerjs/meta#139]
Hey, i would like to do one event BeerJS at Bagé, RS - Brasil. Can you create a repo? Thankfull!!

**Comment by jordanpapaleo** [comment]
Hi

I need you to fill you the issue template completely so I can correctly create your repo.  Please fill in the following:

```
What will you repo be named?

Who will be your admins?

Do you have twitter handles I can include in announcing your new chapter?
```

**Comment by irioborges** [comment]
What will you repo be named? bage
Who will be your admins? @irioborges
Do you have twitter handles I can include in announcing your new chapter? No.

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/bage

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You now are apart of a team that has write access to this repo.  **Accept your Github invite to this BeerJS team** if you want to push code to this repo ;)

Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1.  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2. Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3. Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4. Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5. Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

6. Feel free to direct message me on twitter  @jordanpapaleo :)


Thanks,

Jordan
