### ISSUE TITLE
tallinn beerjs

### ISSUE THREAD

**Issue by drownbes** [beerjs/meta#142]
Created repo is empty. I cannot push there anything. Can you fix it?

**Comment by jordanpapaleo** [comment]
You need to accept the invite ;)

![image](https://user-images.githubusercontent.com/1728807/43857495-4edbd48a-9b00-11e8-86e4-0bb434ebe59e.png)

![image](https://user-images.githubusercontent.com/1728807/43857541-71599196-9b00-11e8-8be2-68db9e76089c.png)
