### ISSUE TITLE
Add new admin to beerjs/bryansk

### ISSUE THREAD

**Issue by sattellite** [beerjs/meta#160]
Please add new admin @tilvan to https://github.com/beerjs/bryansk

Thanks

**Comment by jordanpapaleo** [comment]
I just added tilvan.  Here is your list:

![image](https://user-images.githubusercontent.com/1728807/53260303-faee9200-3685-11e9-8a2a-307a3e3699ba.png)

Do you still need temasmirnov?  He has not accepted.
