### ISSUE TITLE
Maybe Beer.js could get the webpage Beer.js.org

### ISSUE THREAD

**Issue by TheKnarf** [beerjs/meta#162]
[Js.org](https://js.org/) is open for giving out subdomains, maybe beer.js could get the domain beer.js.org.

**Comment by jordanpapaleo** [comment]
Great idea!  Would you be interested in providing the details we need to do this?

**Comment by thblckjkr** [comment]
[Here](https://github.com/js-org/js.org/tree/master) is the main repo of js.org

Basically, you need to have github pages working before taking the CNAME.

To start, you need to create a repo named `beerjs.github.io`, and then let the community create a page for it. Then, we can make a pull request to add some beers to js.org.

**Comment by TheKnarf** [comment]
I'd be happy to help out.

@jordanpapaleo Can you make a repo called `beerjs.github.io`?

**Comment by jordanpapaleo** [comment]
Done! https://github.com/beerjs/beerjs.github.io.  There is a new beerjs team and you are both in it.  It has write access to the repo via pull requests of course.  Have at it and feel free to invite more people to this team.

**Comment by TheKnarf** [comment]
This issue is being tracked in https://github.com/beerjs/beerjs.github.io/issues/2 and can be closed.
