### ISSUE TITLE
Slack invitation request doesn't work

### ISSUE THREAD

**Issue by fharper** [beerjs/meta#163]
I get a "Failed! token_revoked" error when trying to get an invitation using https://beerjs-slack-invite.herokuapp.com/invite

**Comment by jordanpapaleo** [comment]
uggg...ok I will look into this.  I am not even sure who set this up for us or where the code is.   If you give me your email I will manually add you.

**Comment by fharper** [comment]
fharper@oocz.net thanks

**Comment by jordanpapaleo** [comment]
Try this: https://beers-slack-invite.herokuapp.com/invite

**Comment by fharper** [comment]
Thanks, it's working now, but the link was https://beers-slack-invite.herokuapp.com (/invite wasn't found).
