### ISSUE TITLE
New chapter request: Portland, OR

### ISSUE THREAD

**Issue by redmanedigital** [beerjs/meta#165]
# New Chapter Request

What will you repo be named?
portland (a note: i noticed that there's a PDX that was created 6 yrs ago and is not active. I'd be fine with PDX as well if that's easily transferable)

Who will be your admins?
redmanedigital

Do you have twitter handles I can include in announcing your new chapter?
mhalstead

**Comment by jordanpapaleo** [comment]
I just gave you PDX :). Have fun!
