### ISSUE TITLE
Please Add BeerJS/Rocklin

### ISSUE THREAD

**Issue by Frankcarvajal** [beerjs/meta#166]
# New Chapter Request

What will you repo be named? BeerJS/Rocklin

Who will be your admins? @Frankcarvajal

Do you have twitter handles I can include in announcing your new chapter?
Twitter.com/Code_Crafting

We are opening up our meetup to the community of Rocklin CA in the US, a thriving community college & HackerLab community. BeerJS Rocklin will be a fantastic time to get together, pound a few down, and learn collectively about JavaScript. We value good beer, good code, and will forever encourage the sharing of both.

Topics so far have been around ReactJS and the MERN stack, but in we're very open.
Like a familiar BeerJS meetup, the meetup will usually follow a beer socialization/forum format. Anyone can present for any amount of time. You can show something you built, talk about something you would like to build, challenge "best" practices, or change the world; your call. Please let me know if you are interested so we don't double up.

We meet on the 1st Tuesday of the month at Kathrin's Biergarten off Granite Drive. It's tucked into an enjoyable shady spot in the corner with plenty of parking.
For lightning talks etc, HackerLab will host and we can finish off by heading over to Kathrin's!@

Huge thanks to  HackerLab Rocklin & Kathrin's giving us a home in the community.

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/rocklin

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

> **make sure you read the part below**

You now are apart of a team that has write access to this repo.  **Accept your Github invite to this BeerJS team** if you want to push code to this repo ;)

> **make sure you read the part above**

Please create a new issue if you want to modify the contributors to this repository.  Below are some suggestions to help you get you community up and running:

1.  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/reno/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2. Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3. Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.

4. Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5. Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

6. Feel free to direct message me on twitter  @jordanpapaleo or hit me up in our slack channel :)


Thanks,

Jordan
