### ISSUE TITLE
New Admins for Beerjs/berlin 

### ISSUE THREAD

**Issue by Yunnii** [beerjs/meta#170]
🐻 🐝 🍻 

Please add https://github.com/Yunnii and https://github.com/sameoldmadness to https://github.com/beerjs/berlin

Thanks!

**Comment by jordanpapaleo** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1728807/66229619-19465280-e697-11e9-9f90-64e8391f0ff6.png">


There is a single request for access for this team.  bhaskarmelkani?

**Comment by jordanpapaleo** [comment]
Make sure you accept the invite :)
