### ISSUE TITLE
Add new admin to Chelyabinsk

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/meta#179]
Hi! 

Please add @IH8E to https://github.com/beerjs/chelyabinsk as an admin.

🍻

**Comment by jordanpapaleo** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/1728807/73317757-0cbcab80-41ec-11ea-9025-ddc196404f0d.png">

They will need to accept the invite :)

**Comment by igor-shevchenko** [comment]
Thank you @jordanpapaleo!
