### ISSUE TITLE
Ukraine, Kharkiv community

### ISSUE THREAD

**Issue by kiskesis** [beerjs/meta#187]
# New Chapter Request

Where will your community be located: city, state/province/etc, country?
Ukraine, Kharkiv

Who will be your admins?
@kiskesis https://github.com/kiskesis

Do you have twitter handles I can include in announcing your new chapter?
No twitter, telegram: https://t.me/teajskharkiv

**Comment by jordanpapaleo** [comment]
Hi.  Sorry for the delay.  There is already a repo for BeerJS Kharviv: https://github.com/beerjs/kharkiv. The last commit was 5 years ago so i am going to say it's not active.  I am just going to add you to the repo and you can take it over :)

**Comment by jordanpapaleo** [comment]
Please go here and accept the invite: https://github.com/beerjs/kharkiv

**Comment by kiskesis** [comment]
Yep, thanks, I will update it when you add me there.
As I know, old community unactive for a long time)

**Comment by jordanpapaleo** [comment]
It should be ready.  Will you please check

**Comment by kiskesis** [comment]
Hm, dont see access

**Comment by kiskesis** [comment]
> It should be ready. Will you please check

![Uploading Screenshot 2021-07-19 at 17.50.55.png…]()

**Comment by jordanpapaleo** [comment]
Can you hop in the BeerJS slack please https://beers-slack-invite.herokuapp.com/
