### ISSUE TITLE
Hi, I would like to become a member

### ISSUE THREAD

**Issue by lxmarinkovic** [beerjs/meta#188]
# New Chapter Request

Where will your community be located: city, state/province/etc, country?
Stockholm, Sweden. But not necessarily just Stockholm 

Who will be your admins?
Dunno at the moment but mos def someone from JS related meetup groups in the area

Do you have twitter handles I can include in announcing your new chapter?
Nope at the moment, but I will create one as it might be more convenient than meetup for this purpose

**Comment by jordanpapaleo** [comment]
There currently is a repo for Stockholm, https://github.com/beerjs/stockholm.  I added you to that team.  The repo has been dormant for a couple of years.  Have fun!

**Comment by lxmarinkovic** [comment]
Thank you @Jordan ***@***.***> ! :D
