### ISSUE TITLE
Request for Ryazan

### ISSUE THREAD

**Issue by ifedyukin** [beerjs/meta#191]
# New Chapter Request

## Where will your community be located: city, state/province/etc, country?
Russia, Ryazan

## Who will be your admins?
- @ifedyukin

But in the future we will add another admins, I guess.

## Do you have twitter handles I can include in announcing your new chapter?
Ususally we announce our events (meetups and BeerJS parties) in the [Telegram chat](https://t.me/webpurple).
But time to time I post announses in my own twitter - https://twitter.com/ifedyukin

**Comment by ifedyukin** [comment]
Also, repo https://github.com/beerjs/Ryazan already exists. But it wasn't updated since 2018

**Comment by jordanpapaleo** [comment]
I’ll try to get this for you tomorrow 😀

Sent from my smallest computer

On Aug 25, 2022, at 4:42 AM, Igor Fedyukin ***@***.***> wrote:

﻿
Also, repo https://github.com/beerjs/Ryazan already exists. But it wasn't updated since 2018

**Comment by jordanpapaleo** [comment]
![image](https://user-images.githubusercontent.com/1728807/186926476-598b9791-ee37-478d-9934-d4ed9d33820a.png)
