### ISSUE TITLE
I would like to become a member of this organization and contribute here

### ISSUE THREAD

**Issue by hemantwasthere** [beerjs/meta#192]

**Comment by jordanpapaleo** [comment]
What would you like to do?

**Comment by jordanpapaleo** [comment]
No response

**Comment by hemantwasthere** [comment]
ohh sorry for late response, all i want to do is contribute

**Comment by jordanpapaleo** [comment]
To what?  Do you know what BeerJS is?

**Comment by jordanpapaleo** [comment]
Try reading the README file.  This is not a code project; it is a repo for organizing various code communities around the world

**Comment by hemantwasthere** [comment]
Yeah, absolutely

**Comment by jordanpapaleo** [comment]
There are no contributions needed on the `beerjs/meta` repo.

Is there another [project](https://github.com/orgs/beerjs/repositories)  within BeerJS that the represents a city you close to?  You can connect with that group and find out about contributing.

The last option would be to apply start a chapter of BeerJS in your region.  Instructions for that are on the README.
