### ISSUE TITLE
BeerJS Buenos Aires

### ISSUE THREAD

**Issue by bevacqua** [beerjs/meta#23]
Hey guys. I haven't really talked with any of you about this, but I did speak about it with @maxogden and @mikeal, although they're not exactly related to BeerJS (to my knowledge). I'm one of the organizers for NodeSchool / NodeBots in Buenos Aires, and we'd love to branch out. One of those branches would be BeerJS.

I was wondering if I could get access to add our own BA repo here. Thanks! `love(beer && js)`

**Comment by jden** [comment]
I just saw this issue- sorry I dropped it earlier! I've created the repo and the team and added you as an admin: https://github.com/beerjs/buenosaires

¡Salúd! :beers:

**Comment by jden** [comment]
?

**Comment by bevacqua** [comment]
Sweet honey beer! :beer:
