### ISSUE TITLE
Beerjs Jersey City

### ISSUE THREAD

**Issue by cjus** [beerjs/meta#25]
Just created the Jersey City (New Jersey) JavaScript meetup and would like to have a monthly Beerjs meetup.

*github usernames: `cjus`
*name of repo: `beerjs/jc`

**Comment by jden** [comment]
All set! :beers:

**Comment by cjus** [comment]
Awesome thanks!
_Carlos

On Thu, Jan 22, 2015 at 6:41 PM, jden <notifications@github.com> wrote:

> All set! [image: :beers:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/25#issuecomment-71122504>.
>



-- 
_Carlos
--
Contact: http://cjus.me
