### ISSUE TITLE
Rename or new repo for jc

### ISSUE THREAD

**Issue by cjus** [beerjs/meta#26]
I requested a new beerjs repo for Jersey City yesterday and it was promptly created. However, I wasn't thinking broad enough and only later realized that the group is better named "hudson"  which is the name of the county which covers several closely neighboring cities.

Please create the new repo and we can deprecate jc.

Sorry about that. Thanks for you help.

**Comment by jden** [comment]
Not  a problem - GitHub has pretty decent rename support (redirects, etc). Would it work for you if I just renamed the existing repo?

**Comment by cjus** [comment]
Yes thanks.


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: jden <notifications@github.com> </div><div>Date:01/23/2015  1:09 PM  (GMT-05:00) </div><div>To: beerjs/meta <meta@noreply.github.com> </div><div>Cc: Carlos Justiniano <carlos.justiniano@gmail.com> </div><div>Subject: Re: [meta] Rename or new repo for jc (#26) </div><div>
</div>Not a problem - GitHub has pretty decent rename support (redirects, etc). Would it work for you if I just renamed the existing repo?

**Comment by jden** [comment]
All set - https://github.com/beerjs/hudson (also renamed the team to beerjs/hudson, in keeping with the 1:1 team:repo pattern that we have for maintaining local admins)
