### ISSUE TITLE
admin for beerjs/boise

### ISSUE THREAD

**Issue by joshjens** [beerjs/meta#28]
Can I be added as admin for Boise? Looks like there's nothing going on with the group and I want to try and get it going.
j

**Comment by jden** [comment]
Looks like you're all set! I'd also recommend reaching out to my friend @blakedietz (and maybe some other Boise JavaScripters, like @nmartin867

**Comment by joshjens** [comment]
Awesome, will do!

**Comment by nmartin867** [comment]
@joshjens I'm available. I'd like to amp this up as well. We should meet and get something going. The good people at Harrison Hallow offered a venue. I can reach out and make sure that still stands.

**Comment by joshjens** [comment]
Fantastic. I've created a meetup to cross-promote: http://www.meetup.com/BeerJSBoise/
How is Harrison Hallow for food? I want to make sure we have plenty of good food/drink options for non-drinkers. I'm thinking a monthly happy hour to start? Simple intros, good brews.

**Comment by nmartin867** [comment]
It's good! Full menu and they brew their own beer. They are located on the corner of Hill and Bogus Basin; right next to O'Micheal's.

Nick
