### ISSUE TITLE
BeerJS São José dos Campos

### ISSUE THREAD

**Issue by danilovaz** [beerjs/meta#29]
Hello. 

I would like to create a repository for the city of São José dos Campos / SP Brazil. The city's name is huge, so `beerjs/sjc` seems excellent. At the moment only I will be involved in the project, but have already sent invitations to some friends and am awaiting their response =)

Summary -> github username: @danilovaz / repo name: `beerjs/sjc`

Let's drink and code :beers:

**Comment by jden** [comment]
Alright, all set up! https://github.com/beerjs/sjc 

bem vindx! :beers:

**Comment by danilovaz** [comment]
Awesome!
But, I still do not have access to repo/org :cry:  what should be done? Thanks :smile:

**Comment by jden** [comment]
Check your email, you should have received an invitation to the beerjs/organizers and beerjs/sjc groups. the @beerjs/sjc has admin addcess to the sjc repo.

**Comment by danilovaz** [comment]
awesome :smiley: 

thanks :+1:
