### ISSUE TITLE
beerjs: Porto for the JS devs in northern Portugal.

### ISSUE THREAD

**Issue by pachanka** [beerjs/meta#30]
**Porto, Portugal needs :beer:js!**

And I would love to get some _cervejas_ with JS enthusiasts here.

* I'll manage it while more people join in.
* The slug would be `beerjs/porto`. 
* Thanks.

**Comment by nibbleshifter** [comment]
Where, when and Sagres or Super Bock?

**Comment by jden** [comment]
Great idea! You're all set, @pachanka - https://github.com/beerjs/porto is yours. :beers:
