### ISSUE TITLE
BeerJS NYC?

### ISSUE THREAD

**Issue by moimikey** [beerjs/meta#31]
**very** surprising that there isn't an NYC chapter... I'm not the most managerial of people, but I am one for providing updates and conversation. I would not be opposed to pairing with someone as ownership, or in the interim, solely handling that. But like I said, not the most managerial of people :)

would vote for **beerjs/nyc**

![tumblr_inline_nbfvclqelk1qznfri](https://cloud.githubusercontent.com/assets/182661/6718043/226134e4-cd87-11e4-8033-7280fb331eb0.gif)

**Comment by derek** [comment]
Beer.js in NYC would be a welcome addition!  I wouldn't worry too much
about the managerial/organizational aspect of the group.  I don't know how
other cities do it, but managing the one in SF takes about 5 minutes per
month, as all it consists of is posting details to meetup.com, Github, and
a few tweets.

Cheers!

**Comment by moimikey** [comment]
in that case, i'd be open to repping nyc. i can do it solely and gradually add some friends.

**Comment by jden** [comment]
Alright, @moimikey - https://github.com/beerjs/nyc is all yours. I'd recommend chatting with some of the other meetup organizers in the area - I know there's a pretty healthy network of events going on there. Cheers & :beers:
