### ISSUE TITLE
Austin, Tx beerjs

### ISSUE THREAD

**Issue by mtrussell** [beerjs/meta#32]
I would love to see a beerjs in Austin. I am currently the only one I know to be an admin.

username of admin: mtrussell

name of repo: beerjs/atx

Sorry, no gifs...

Thanks for putting this together. I'm looking forward to organizing an event!

**Comment by jden** [comment]
Alright, you're all set up! https://github.com/beerjs/atx :beers:

**Comment by mtrussell** [comment]
Awesome! Thank you!
