### ISSUE TITLE
beer.js - Sorocaba, Brazil

### ISSUE THREAD

**Issue by brenolf** [beerjs/meta#33]
We would like to spread the word in Brazil! We are currently studying CS at Federal University of São Carlos and would love to allocate a time in our yearly event for beer.js!

**Admins:** @brenolf and @mccraveiro

**Name:** beerjs/sorocaba

**Gifs/Emojis:** We have no gifs/emojis to share yet :-(

**Comment by jden** [comment]
You're all set up! :beers: https://github.com/beerjs/sorocaba

**Comment by brenolf** [comment]
Thank you! :beers:
