### ISSUE TITLE
Sticker buy?

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/meta#36]
Are any organizers interested in doing a group buy of BeerJS stickers? I don't have enough folks in Albuquerque interested to make a BeerJS ABQ sticker worthwhile, but folks would like generic ones.

**Comment by moimikey** [comment]
@orbiteleven sorry for being 28 days late but i was literally just about to post this! BeerJS NYC would love stickers too :o

**Comment by moimikey** [comment]
@cramforce @voodootikigod @jden :santa:

**Comment by jden** [comment]
There used to be stickers available from the jsconf store, but it appears to be offline now. The source files for the logo are at https://github.com/voodootikigod/logo.js/tree/master/beerjs

If anyone wants to put together another order, or has some way to make it easy to take small orders through a website or something, feel free to post here.

/cc @beerjs/organizers

**Comment by MathRobin** [comment]
Some guys (most of them) coule be really interested in in Paris :-)

**Comment by jordanpapaleo** [comment]
Tahoe group would be interested too

**Comment by scarabaeus** [comment]
Just did a "Beer.js Tallahassee" sticker buy (50) from Sticker Mule to see how they turn out (and to hand out at our inaugural event), but I'll throw down on some generic ones if you guys are getting something together.

![Beer.js Tallahassee Logo](https://raw.githubusercontent.com/beerjs/tallahassee/master/img/beerjs-tallahassee.png)

**Comment by jordanpapaleo** [comment]
So stickers are pretty cheap.  You can get 100 for $60 from sticker mule.  I just did hex sticker for Tahoe 
![image](https://cloud.githubusercontent.com/assets/1728807/12693779/60ef438a-c6ca-11e5-8b3d-78ea89089f65.png)
  The issue with a group order is that one person has to order them then ship them around the world.  It seems like it would be much easier if there was a easy way for you guys to order them.  If people are interested I will contact sticker mule and see if there is something we can do to place a order for multiple locations.  I would like a confirmation of those who are interested though.  

Thanks,

Jordan 
/beerjs/tahoe

**Comment by vrivas** [comment]
Thanks for your offering, but as far as I can see, sending the stickers
(from sticker mule) to Spain is quite expensive (more that the stickers
themselves).

If it helps, I'm making my own stickers, just printing in an adhesive
sheet... after this, my sons do the "hard" work with the scissors :D

You can download de odt file from
https://github.com/beerjs/jaen/blob/master/assets/stickers.odt

Cheers!

2016-01-30 5:55 GMT+01:00 Jordan Papaleo <notifications@github.com>:

> So stickers are pretty cheap. You can get 100 for $60 from sticker mule. I
> just did hex sticker for Tahoe
> [image: image]
> <https://cloud.githubusercontent.com/assets/1728807/12693779/60ef438a-c6ca-11e5-8b3d-78ea89089f65.png>
> The issue with a group order is that one person has to order them then
> ship them around the world. It seems like it would be much easier if there
> was a easy way for you guys to order them. If people are interested I will
> contact sticker mule and see if there is something we can do to place a
> order for multiple locations. I would like a confirmation of those who are
> interested though.
>
> Thanks,
>
> Jordan
> /beerjs/tahoe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/36#issuecomment-177067427>.
>



-- 
*Victor Manuel Rivas Santos*

**Comment by samt** [comment]
I was thinking about doing a sticker buy, if people are still interested, I can buy a bunch and ship to US, Canada, and Europe. I may be able to get the cost of the production sponsored :smile:

**Comment by jordanpapaleo** [comment]
I can send you a sticker mule link for this.  All proceeds from purchases will go back into buying more stickers and hopefully being able to share the love with all the groups.

**Comment by jdorfman** [comment]
@samt if you ever need any for the future email me: jdorfman at stickermule.com

**Comment by jordanpapaleo** [comment]
See update in the README.md
