### ISSUE TITLE
BeerJS in SP

### ISSUE THREAD

**Issue by thebergamo** [beerjs/meta#38]
Hello Everybody!

I would like fork beerjs in my city! São Paulo in Brazil!

What is the next steps?

**Comment by jden** [comment]
Hi @thebergamo, and thanks for your interest! Per https://github.com/beerjs/meta#fork-a-beerjs-in-your-city now we just need

- **the github usernames of everyone who should be an admin on the repo**. we find that having at least 2 is best, but if it's just you, that's fine for now.
- **the name of the repo**. this becomes the url slug, eg `beerjs/foo`. if your city has a short name, like an airport code, that's fine. whatever you like that's still recognizable as your city.
- **bonus: gifs or emoji** are always welcome

**Comment by thebergamo** [comment]
Well, 

* Now, only me as admin. In next months maybe some other peoples can candidate for this place and maybe override me.

* I change the repo name to "sp". I need send the repo to BeerJS?

**Comment by jden** [comment]
Ok, you're all set up - https://github.com/beerjs/sp (you may have to accept the invite in your email)
