### ISSUE TITLE
Problem about the name

### ISSUE THREAD

**Issue by MathRobin** [beerjs/meta#40]
Some of Paris members shows a main problem.

Some people don't frink alcohol, some of us are women, some of us are vegetarian, some of us are religious. All of them like us as to have the respect of each other.
BeerJS is a name, just a name, but implies the "usage" of alcohol, that don't correspond to a part of us.

The goal of this meetup is to be a great cool community to met other people from differents tech meetups. Even if there is alcohol or not.

We should find another name, for groups which wants it, which don't refers to alcohol. Which don't naturally excludes people.

Sorry for my english

**Comment by revolunet** [comment]
This is getting ridiculous. 

BeerJS is open to everyone, its just a funny name. we just need to add on the meetup page : "open to everyone" even if its implicit for us.

The main word in "open source" community is "open".

If anyone wants to create some other event, just tell someone from FranceJS meetup group and we will add you as event organizer so you can create you "SushiJS", "WtfJS" or whatever

**Comment by revolunet** [comment]
and let's discuss this IRL

**Comment by skinnyfoetusboy** [comment]
The question that was originally raised here was not about the name, which is perfectly fine _per se_.
The event is about drinking beer while discussing JS, **that** is your niche. 

What irks me, however, was the male-centered vision of the whole thing. There is no need to make it a "bro-event" as this gives the impression that : 
- JS is for dudes
- Beer is for dudes
- This is your ~secret boys club no girls allowed~

Beer-drinking is _not_ the problem, your attitude about it is.

**Comment by revolunet** [comment]
yep labelling the event "beers & bros" was an "error", fixed since :) BTW i can predict it perfectly described what will happen tonight, with that name, or another.

**Comment by skinnyfoetusboy** [comment]
Maybe it wouldn't if you had been more inclusive since the start.

**Comment by revolunet** [comment]
from memory, "bros" was never used before. we used to have "Trolls and Beers"

**Comment by molokoloco** [comment]
Dur d'être créatif ! J'essaie de trouver une punch line pour chaque event que l'organise, cette fois-ci des gens qui ne venaient pas ont été choqués. Dommage ce n'était pas le but...
Gardez l'esprit critique et ouvert quand même... "beers & bros" n'était pas vraiment une "erreur" et l'appeler PrincessJS ne fera pas venir plus de filles hélas. L’événement peut évoluer au fur et à mesure que la communauté qui le compose évolue.
Sur la mailing ParisJS il n'y a pas de message de filles et encore moins de filles "actives" dans la communauté. https://groups.google.com/forum/#!aboutgroup/parisjs je ne me rappel pas qu'on les aient exclu pourtant.
C'est quoi leur problème ?

**Comment by molokoloco** [comment]
Et les mecs, pas la peine de parler à leur place, c'est hyper macho comme comportement.

**Comment by MattiSG** [comment]
Il y a plusieurs sujets, qu’il vaudrait mieux ne pas mélanger si on veut avoir une discussion saine :

1. Le titre « BeerJS ».
2. Le titre de l'événement « Beers & Bros ».
3. L'accroche « Open to all bros 🍻 ».
4. Les réponses de @molokoloco face aux réactions de la communauté.

Personnellement, j'ai [réagi](http://www.meetup.com/FranceJS/events/223306625/comments/450643368/) sur **3**. [Indépendamment](https://twitter.com/railsgirlsparis/status/611285206515994624), RailsGirls a réagi sur **2**, et @tchak a [élargi](https://twitter.com/tchak13/status/611289703892021248) à **1**. Puis un peu tout le monde s'est accordé sur **4**.

Je rejoins @revolunet sur le fait qu’il serait de meilleur aloi de traiter ce(s) problème(s) IRL plutôt que par des médias textuels.

Pour autant, avant de participer à une telle discussion, il serait important pour moi que l'on s'accorde sur quelques éléments de médiation et de résultats attendus, car j'appréhende l'efficacité d'échanges avec @molokoloco au vu à la fois de son comportement habituel et de ses prises de position (ou [trolls](https://github.com/beerjs/meta/issues/40#issuecomment-113115501)), tant ici que sur Twitter et Meetup.

Dans tous les cas, je considère que la réaction de la communauté a été efficace, que les actions de ceux qui pouvaient agir étaient correctes, et que les points 2 et 3 ont été traités. Sauf réitération, pas d'urgence pour moi pour en reparler.

**Comment by molokoloco** [comment]
Matti SG, c'est gentil de <b>te soucier des filles dans un événement ou tu ne viens pas et ou aucune fille n'a répondu présente</b>.


J'en ai organisé 5 ou 6 cette année. une fille était inscrite au dernier http://www.meetup.com/FranceJS/events/221844510/ mais elle n'est pas venu, pourtant voici la description de l’événement :

BeerJS Paris XIII : Trolls + Beers

April 21 · 7:00 PM
Café le Troll
Let's drink some beers and have fun ! :)

BeerJS Paris 13e édition ! :)  
10 sur meetup et 3 d'avant l'époque "Meetup"... déjà ! 
Come on, open to all front and back avengers !


C'est toi le Troll. Va plutôt parler avec elles et comprendre ce qu'elles cherchent vraiment, avant de venir t'attaquer à moi personnellement en prenant un sujet dont tu te fiche.

**Comment by revolunet** [comment]
hey guys, nous sommes tous ouverts et souhaitons tous élargir le public de ces events. Il se trouve que dans les faits ya que des bros, donc discutons plutôt IRL de comment faire évoluer ce status quo;

**Comment by tchak** [comment]
> Et les mecs, pas la peine de parler à leur place, c'est hyper macho comme comportement.
T'est allé leurs parler toi ?

> The event is about drinking beer while discussing JS, that is your niche.
If this is the intent of the event, it's perfectly fine. But it means I will not be coming to the events.

I agree that what matters is to be clear about what this event is about. There is nothing wrong with trolling and drinking, it just something I have no interest in. And like it or not, both of these activities are anything but inclusive. Again, nothing wrong with that. This is free country, everyone can spend the time and energy the way they want :)

So it is not about "is it ok to drink beer?". It is about "what we want to accomplish?". I have no problems with people having good time at #BeerJS. I think we tried to take on the wrong problem here. This event was newer about inclusion, and again it is fine by me. We can't make everything inclusive.

**Comment by molokoloco** [comment]
C'est un homme qui s'exprime sur le compte "@RailsGirlsParis", un des protagonistes à l'origine de la polémique... https://twitter.com/RailsGirlsParis/status/611289976702169088

**Comment by skinnyfoetusboy** [comment]
So _fucking_ __what__ ?

**Comment by jden** [comment]
Apologies in advance, I don't speak French well at all and am therefore commenting just based on the English comments in this thread.

@MathRobin thank you for raising this issue! I really appreciate you expressing your concerns. Several people in this thread have behaved inappropriately and in matters counter to the [BeerJS Code of Conduct](https://github.com/beerjs/meta#code-of-conduct).

@revolunet, @skinnyfoetusboy, your comments in this thread have been unacceptable. Please stop posting in this thread. Continued violation of our community code of conduct will result in your exclusion from the community.

BeerJS is about creating social spaces to strengthen software communities. there is no requirement to drink to participate, but (like several people have pointed out above), it is a social setting that not everyone wants to participate in. If you feel that way, I hope that you'll think of whatever your favorite social environment is and create a group around that, like [sushiJS](https://github.com/sushijs).

BeerJS takes the traditional meetup format of having one or two speakers get up in front of a room of people who have just eaten pizza and beer, and removes the speakers and slides. It gives people a chance to meet other developers and have face to face conversations about new projects and ideas.

Like any group of people, BeerJS is not immune from people doing horrible things to each other. It is the responsibility and obligation of BeerJS organizers to make participants aware of our code of conduct and enforce it. Local groups should discuss what type of communities they want to have and actively work to make them better.

**To be clear: if a local group is not abiding by the code of conduct, it will no longer be affiliated with BeerJS** and will be publicly removed from any listing or association with the BeerJS github group. We've never had to do it so far, but it is certainly on the table as a consequence.

**tl;dr:** not everyone may enjoy or be interested in BeerJS, but no one should feel excluded from BeerJS for harassment, fears for their personal safety, or generally antisocial behavior. This type of behavior is not the purpose of BeerJS and it will not be tolerated. This behavior should be reported. You can report it by filing a public github issue or by sending me an email, jason@denizac.org

**Comment by jden** [comment]
@MathRobin could you please email me at jason@denizac.org with specific information about the Paris BeerJS group that lead you to open this issue, and what course of action you think is appropriate? Thank you for opening this issue.

**Comment by revolunet** [comment]
sorry i dont get it... what was "unacceptable" for me ?

**Comment by skinnyfoetusboy** [comment]
@jden Excuse me in advance but I think you didn't understand what I was saying. 
I was advocating for a _more_ inclusive Parisian BeerJS.
The one that takes place today had "beers and bros" as its subtitle and a few people felt that could be offensive to women in the community.

Never have I said that we should create a sushiJS or whatevs.

**Comment by jden** [comment]
@revolunet you response to the original complaint was dismissive, defensive, and condescending.
@skinnyfoetusboy I deleted a comment that you made lower in this thread that seemed inflammatory and not constructive. it is possible that I took it wrong

**Comment by skinnyfoetusboy** [comment]
@jden That comment was an answer to the allegation by @molokoloco that "there are no girls in the community anyway".

**Comment by jden** [comment]
This is the event in question: http://www.meetup.com/FranceJS/events/223306625/
@revolunet is listed as the event organizer on meetup. Please change the name of the event - "Trolls and Drinks" is not appropriate messaging for an event affiliated with BeerJS.

**Comment by voodootikigod** [comment]
@jden :+1:

@revolunet the Trolls and Drinks needs to be removed XOR the BeerJS needs
to be removed. As the originator and owner of the BeerJS event and
namesake, I will not stand for the blatant standoff nature of this thread.
We are trying to provide avenues and channels for people to engage and
become involved -- this has thus far done the exact opposite. The "Trolls
and Drinks" subtitle is unacceptable within the BeerJS community, if you
decide you want to hold on to that, please name your event just that and it
shall be excluded from the BeerJS community.

Thank you,

*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*The things I make that you should check out:*
SaferAging <http://www.saferaging.com/> | JSConf <http://jsconf.com/> |
RobotsConf <http://robotsconf.com/> | RobotsWeekly
<http://robotsweekly.com/>

Help me end the negativity on the internet, share this
<http://jsconf.eu/2011/an_end_to_negativity.html>.

**Comment by molokoloco** [comment]
Ok i give up on that.
Sorry for the Parisian #BeerJS community driving i have done since some years.
Some male, not involved, and at the origin of this issue (@matti_sg_fr , @RailsGirlsParis aka @abelar_s, @skinnyfoetusboy etc) have destroyed something, "speaking in the name of girls")

I delete the event and there will be no other from me.

Good ? everybody Ok ?

Now go fuck away.

**Comment by revolunet** [comment]
Guys, i dont mind at all about the naming of the event and sorry if my answer was dismissive... i really think there is big confusion here due to language barrier and the fact that the discussion did not start here.

renamed to : "DrinksJS Paris - Trolls and Drinks". sorry if it hurt you.

BTW, can you explain whats wrong with "Trolls and drinks" ? 

not native english so i may add a bit more confusion :)

**Comment by revolunet** [comment]
Noooooo @molokoloco

**Comment by revolunet** [comment]
this is a shame

**Comment by revolunet** [comment]
and i used "guys" again ! slap me hard

**Comment by jden** [comment]
I'm sorry to hear about the decision to keep the troll aspect and drop the BeerJS name. I have removed the BeerJS/Paris repository and group.

**Comment by voodootikigod** [comment]
@molokoloco I am not sure I fully understand the dramatic response, but let me provide you the reverse view, especially since you have done years of BeerJS Parisian events. I started this (along with many things) that people utilize and take advantage of the benefits thereof, it is a lot of labor, blood, sweat, often tears, and learnings that get shared and spread around for the benefit of many. Trust me, I understand your initial angst, but I would hope you can also understand and see my concern and need for vetting issues within the communities I have helped create and foster. I would suggest though taking a step back, relax, and then re-engage (if so desired).

@revolunet What is wrong with "Trolls and Drinks" is it is revisionist. BeerJS doesnt need a tagline, its not necessary. The [tweets](https://twitter.com/BeerJS_Paris/status/611172336130256896) are already in the general feed for `beerjs` and as such effect the global community.

**Comment by revolunet** [comment]
ha yes, the name of the Bar we go is "Le Troll" :)

BTW in reaction to this epic and unexpected situation i just bought drinksjs.com - not alcohol-related, and a simple CoC : "welcome everyone"

@jden @voodootikigod please come and say hi if you're in Paris, should be easier to understand each other IRL !

**Comment by voodootikigod** [comment]
@revolunet perfect solution. Thank you. Next time I am in Paris, I will take you up on that! :coffee:

**Comment by revolunet** [comment]
cool, sorry for the noise.

**Comment by revolunet** [comment]
I'd like to personally thanks the people who raised this local issue here, never came to this local event, and dont even know @molokoloco

**Comment by derek** [comment]
@revolunet DrinksJS is a dandy idea.  Though if you are considering a fork, I've often heard ideas (and seen attempts in SF w/ JS Hangouts & JavaScript Club) at creating a larger umbrella group for social JS activities.  This would include things like beer, drinks, and sushi, but also others like hiking, sports, hackathons, movies, etc.  Beers and drinks are of course the easiest to organize, but there's demand for others as well.  Just some food for thought.

**Comment by olivvv** [comment]
This thread shows how a lazy paternalistic attitude can make of an event open to every idiot an event limited to those who master the cultural codes and specific language policies from another country. (google ethnocentrism)

A club of rich kids congratulating each other on how open they are.

**Comment by tchak** [comment]
@jden @voodootikigod can we close this thread? The comments coming in are not helpful.
I think the point was made (tank you for this).
We are going to figure out what next at the local, not "google ethnocentric", scale. Yes @olivvv, sarcasm was intended.

**Comment by jden** [comment]
@tchak yes. The thread was closed, which is normally enough of an indication on github. As your request, I will lock this thread.
