### ISSUE TITLE
Looking for organizer: Beer.js Amsterdam

### ISSUE THREAD

**Issue by yoshuawuyts** [beerjs/meta#42]
I'll be permanently moving to Australia soon, and I was wondering if anyone is interested in taking over Beer.js Amsterdam. 

There's been one get-together so far, and the people that attended were absolutely lovely. Since then about 100 more people have joined the group, and with [international beer.js day](https://github.com/beerjs/meta/issues/41) being planned it would be ideal to host another event. Let me know if you, or anyone you know would like to organize future Beer.js Amsterdam events. Cheers! 🍻

- [meetup.com/beerjs-amsterdam](http://www.meetup.com/beerjs-amsterdam/)

**Comment by jden** [comment]
@yoshuawuyts have you asked on the meetup group as well? When you find someone, let us know and we'll add them to the @beerjs/amsterdam team

**Comment by yoshuawuyts** [comment]
@jden Good suggestion, just messaged the meetup members! ✨I'll let you know if I find anyone.

**Comment by jbnicolai** [comment]
@yoshuawuyts @jden I'd be happy to help out. I live and work in Amsterdam myself, and am fairly active in the nodejs community

**Comment by yoshuawuyts** [comment]
@jbnicolai dope! :tada: Can you send your contact details to yoshuawuyts[at]gmail so I can add you to the meetup page? Thanks! :grin:

**Comment by jden** [comment]
Great! I added @jbnicolai to @beerjs/amsterdam and /organizers, which will give you admin access to the https://github.com/beerjs/amsterdam repo

**Comment by jbnicolai** [comment]
Excellent, thanks a lot guys :)
