### ISSUE TITLE
Lala BeerJS

### ISSUE THREAD

**Issue by cendaeg** [beerjs/meta#44]
Hello! I am very interested in opening up a BeerJS in the Greater Lafayette area in Indiana. Here is the information!

**Admins**: Just me right now, @cendaeg
**Repo name:** Lala - this will cover the cities of West Lafayette and Lafayette

Cheers!
@cendaeg

![space core](https://cloud.githubusercontent.com/assets/2363236/8674005/0fce7556-2a09-11e5-943e-c47d69a4d374.gif)

**Comment by cendaeg** [comment]
Any word about this? I haven't heard back.

**Comment by vrivas** [comment]
It seems like not being very active this repo :(
Let's wait... there's no much we can do, isn't it?

**Comment by jden** [comment]
@cendaeg sorry for this issue falling through the cracks! I've created the repo and invited you to the @beerjs/lala team (which has admin access).

:beers:

**Comment by cendaeg** [comment]
No problem! Thanks!
