### ISSUE TITLE
BeerJS Palo Alto

### ISSUE THREAD

**Issue by terinjokes** [beerjs/meta#45]
I've taken over stewardship of BeerJS Palo Alto's meetup and organized a successful July meetup, and already scheduled a meetup for August.

Unfortunately, I can't update folks who are watching the GitHub repo.

Can I be added to the team for https://github.com/beerjs/paloalto ?

**Comment by jden** [comment]
Have you tried contacting @potch? I'm happy to add and update people to the local github team as needed, but just trying to keep everyone looped in.

**Comment by terinjokes** [comment]
I have not, but now I feel bad about it. Sorry @potch.

**Comment by jden** [comment]
Paging @potch. @terinjokes I'd be happy to add you to the @beerjs/paloalto team if you're still interested

**Comment by terinjokes** [comment]
@jden I still am.

**Comment by jden** [comment]
@terinjokes invited.
