### ISSUE TITLE
Would it be possible to create beerjs/jaen?

### ISSUE THREAD

**Issue by vrivas** [beerjs/meta#46]
Hi!
I'm Victor Rivas, from the University of Jaen, in the south of Spain.
It would be great if we could create beerjs/jaen, so, please, consider it.
At this moment, I would be the only admin, but I'm sure we'll be able to add one or two more people in the next weeks.
Thanks.
And beers.

**Comment by jden** [comment]
sorry for the delay in responding to @beerjs/meta tickets - I've been busy starting a new job.

I've created the repo and invited @vrivas to @beerjs/jaen group (which has admin access to the repo).

¡Salud! :beers:

**Comment by vrivas** [comment]
Thanks a lot!
Best wishes for your new job!
