### ISSUE TITLE
BeerJS/Chicago

### ISSUE THREAD

**Issue by befreestudios** [beerjs/meta#48]
I'd like to get a beerjs/Chicago chapter going!! Thanks

**Comment by lukewestby** [comment]
:+1: i'd love to coorganize if you are looking for assistance

**Comment by befreestudios** [comment]
Absolutely!!! I was planning on coming to your redux talk, but something came up and I couldn't make it. But yea, lets talk and get something goin!

**Comment by twolfson** [comment]
If you wind up organizing something, please post the info here. I would be interested in attending =)

**Comment by befreestudios** [comment]
@voodootikigod @cramforce @jden 
Administrators would be me (@befreestudios) and @lukewestby 

Let me know if you need anything more from me to get this rolling. Thanks!!!

**Comment by jden** [comment]
@befreestudios sorry for the delay in responding to @beerjs/meta tickets - I've been busy starting a new job.

Happy to see interest in Chicago! I've created the repo and invited @befreestudios and @lukewestby to the @beerjs/chicago group (which has admin access to the repo). Let me know in this thread if @twolfson wants admin access as well. 

Cheers! :beers:

**Comment by jden** [comment]
Closing this issue for now- feel free to reopen or create a new issue if needed

**Comment by lukewestby** [comment]
thanks @jden!

**Comment by befreestudios** [comment]
excellent, Thank you @jden !!
