### ISSUE TITLE
I've been asked to open also the beerjs at Granada

### ISSUE THREAD

**Issue by vrivas** [beerjs/meta#50]
Hi, again!!
I'm currently managing the beerjs at Jaen (where I work), and have been asked to also organize the beerjs at Granada (where I live). 
Please, consider the possibility of this proposal.
The admins would be myself (https://github.com/vrivas) and also JJ Merelo (https://github.com/JJ).
Thanks,
Victor

**Comment by jden** [comment]
Excellent, I have created https://github.com/beerjs/granada and added you and @jj to @beerjs/granada group which has admin permissions to the repo. Cheers! :beers:

**Comment by JJ** [comment]
Thanks!

**Comment by vrivas** [comment]
OK. Thanks!
The README is already updated.
Cheers!

2015-10-25 23:08 GMT+01:00 Jason Denizac <notifications@github.com>:

> Excellent, I have created https://github.com/beerjs/granada and added you
> and @jj <https://github.com/jj> to @beerjs/granada
> <https://github.com/orgs/beerjs/teams/granada> group which has admin
> permissions to the repo. Cheers! [image: :beers:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/50#issuecomment-150979377>.
>



-- 
*Victor Manuel Rivas Santos*
