### ISSUE TITLE
Create a BeerJS Slack

### ISSUE THREAD

**Issue by jden** [beerjs/meta#51]
From https://github.com/beerjs/chicago/issues/1#issuecomment-151252985

It looks like beerjs.slack.com is taken - do we know anything about it? If there's already one, it would be good to converge there. If not, I'm happy to make one with another team subdomain. /cc @beerjs/owners

From the above-referenced issue:

> have channels for each city and also meta channels for general discussion and issues

This sounds like a good plan to me.

**Comment by scarabaeus** [comment]
+1

**Comment by jordanpapaleo** [comment]
@jden Any update on this or anything I can do to help out?

**Comment by jden** [comment]
I was never able to figure out who has the beerjs.slack.com account, and as far as I can tell it's inactive. Probably the best course is to pick a different subdomain and then set it up and let everyone know.

**Comment by jordanpapaleo** [comment]
Ill look into it.

Cool if I add myself to the README.md page for a contact?

**Comment by jden** [comment]
> Cool if I add myself to the README.md page for a contact?
absolutely. In fact, probably best to remove me, because I can't guarantee a response time (and in fact will likely be pretty hit-or-miss)

**Comment by jordanpapaleo** [comment]
So should I be the primary point of contact?  How involved are the other guys?

**Comment by vrivas** [comment]
2016-01-30 6:07 GMT+01:00 Jordan Papaleo <notifications@github.com>:

> Ill look into it.
>
> Cool if I add myself to the README.md page for a contact?
>
> > On Jan 29, 2016, at 9:05 PM, Jason Denizac <notifications@github.com>
> wrote:
> >
> > I was never able to figure out who has the beerjs.slack.com account,
> and as far as I can tell it's inactive. Probably the best course is to pick
> a different subdomain and then set it up and let everyone know.
>

Do you think it would be possible to contact with Slack admins so that they
remove that account? If, as you say is inactive, we could show them that
there exist an active community in Github that wants to use the same id in
Slack?




> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/beerjs/meta/issues/51#issuecomment-177069107>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/51#issuecomment-177069206>.
>



-- 
*Victor Manuel Rivas Santos*

**Comment by jordanpapaleo** [comment]
We now have https://beerjs.slack.com.  I'll update the README.md once it is setup.

**Comment by jordanpapaleo** [comment]
So I am not going to be setting up auto invite right now/  Too much to do.  If anyone wants to jump on that let me know.  Until then just post your email to this issue and I will add you to the channel.  You can then invite whoever you want to it

**Comment by vrivas** [comment]
vrivas@ujaen.es
Thanks, @jordanpapaleo

**Comment by thejohnsmith** [comment]
john@thejohnsmith.com

**Comment by jden** [comment]
Looks like you can one-click deploy the auto invite application to a heroku free tier instance: https://github.com/outsideris/slack-invite-automation

**Comment by jordanpapaleo** [comment]
Cool.  Ill check it out. 

Thanks Jason

**Comment by jordanpapaleo** [comment]
I am in the middle of a Parse catastrophe.  I will try to look at the slack invite repo but it may be next week.  If anyone wants to take a peek and comeback with some cliff notes.. Yeaahhhh that would be awesome.

**Comment by maasencioh** [comment]
Hi, mine is maasencioh@gmail.com

**Comment by jden** [comment]
Anyone wanna give this a try and report back if it works? https://beerjs-slack-invite.herokuapp.com/

I've moderated out the comments with email addresses.

**Comment by vrivas** [comment]
It worked for me!!

2016-02-11 8:45 GMT+01:00 Jason Denizac <notifications@github.com>:

> Anyone wanna give this a try and report back if it works?
> https://beerjs-slack-invite.herokuapp.com/
>
> I've moderated out the comments with email addresses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/51#issuecomment-182751856>.
>



-- 
*Victor Manuel Rivas Santos*

**Comment by jden** [comment]
:+1: :beers:
