### ISSUE TITLE
Added a new admin to beerjs/jaen

### ISSUE THREAD

**Issue by vrivas** [beerjs/meta#52]
Hi!
beerjs/jaen has a new admin, apart from myself. He is joseja8. Just for you to know, in case you want to store this information somewhere.
Cheers!

**Comment by jden** [comment]
Great, I've added @joseja8 to @beerjs/jaen and beerjs/organizers

**Comment by vrivas** [comment]
great!!
Thanks!

2015-11-16 18:47 GMT+01:00 Jason Denizac <notifications@github.com>:

> Great, I've added @joseja8 <https://github.com/joseja8> to @beerjs/jaen
> <https://github.com/orgs/beerjs/teams/jaen> and beerjs/organizers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/52#issuecomment-157116688>.
>



-- 
*Victor Manuel Rivas Santos*
