### ISSUE TITLE
Tallahassee, Florida Repo Creation Please!

### ISSUE THREAD

**Issue by scarabaeus** [beerjs/meta#53]
Hey guys...  I wanted to set up a beerjs in Tallahassee, FL.  Please let me know if you need anything else.  Thanks!

__The github usernames of everyone who should be an admin on the repo:__

scarabaeus  _(All by my lonesome right now, but I'll get another person)_

__The name of the repo. this becomes the url slug, eg beerjs/foo:__

tallahassee

**Comment by jden** [comment]
I've created the https://github.com/beerjs/tallahassee repo and added you to the @beerjs/tallahassee team which has admin access to that repo. I've also invited you to the beerjs/organizers team. Welcome aboard! :beers:

**Comment by scarabaeus** [comment]
Thank you @jden!!  I appreciate it!

**Comment by scarabaeus** [comment]
Maybe I'm just having a newb moment, but I don't seem to have access to the repo:

Pushing to https://scarabaeus@github.com/beerjs/tallahassee.git
remote: Permission to beerjs/tallahassee.git denied to scarabaeus.
fatal: unable to access 'https://scarabaeus@github.com/beerjs/tallahassee.git/': The requested URL returned error: 403

**Comment by jden** [comment]
It shows you haven't accepted the invitation to join the group - check your email and click the link to accept it

**Comment by scarabaeus** [comment]
Oh geez...  Yep. There it is.  My bad, man.  Thank you again!
