### ISSUE TITLE
MSP (Minneapolis/St. Paul) beerjs

### ISSUE THREAD

**Issue by markscripter** [beerjs/meta#56]
I'd like to create a beerjs community in Minneapolis/St. Paul (MN).

I'll be the admin for now (markscripter) until I can get others and the name of the repo can be 'msp'.

Let me know if you need anything else.

Thanks,
Mark

**Comment by jden** [comment]
All set! Check your inbox for the invitation to the @beerjs/msp team which has admin to the repo. 

Cheers :beers:

**Comment by markscripter** [comment]
Awesome! Thanks for the quick response!
