### ISSUE TITLE
Add User

### ISSUE THREAD

**Issue by FMCalisto** [beerjs/meta#58]
I am a Web Developer and I would like to contribute to your Projects and Code, from Lisbon - Portugal.

Please add me:

**Username:** FMCalisto
**Repo Name:** ```beerjs/lisbon```
[Lisbon GIF](http://49.media.tumblr.com/2539a3ab71261bdec1f2ca29825de4ef/tumblr_nkyhfivURU1sg8vhlo1_500.gif)

**Comment by jden** [comment]
All set- https://github.com/beerjs/lisbon and I've added you to the @beerjs/lisbon team, which has admin access to the repo. Please open another issue if you ever need to add another admin.

Bem vindx!

:beer:
