### ISSUE TITLE
BeerJS in Bogotá

### ISSUE THREAD

**Issue by maasencioh** [beerjs/meta#59]
I'd like to create a BeerJS community in Bogotá, Colombia.

I'll be the admin for now (@maasencioh) until I can get others and the name of the repo can be `bogota`.

Let me know if you need anything else or have any advice.

Best regards,
Miguel

**Comment by jden** [comment]
Sure thing- I created https://github.com/beerjs/bogota, and added you to @beerjs/bogota which has admin access to the repo.

Cheers,

:beers:
