### ISSUE TITLE
beerjs/newcastle

### ISSUE THREAD

**Issue by stevenjob** [beerjs/meta#60]
Hello! I would like to organise BeerJS in Newcastle Upon Tyne, UK.

Admins: @rjmcneill , @jdhodges431 , @stevenjob

Preferred name: beerjs/Newcastle

Thanks :beers:

**Comment by jden** [comment]
All set! Repo at https://github.com/beerjs/newcastle, plus I've added the three of you to @beerjs/newcastle team with admin access (check your email for the team invite, you have to click through to accept).

 :beers:
