### ISSUE TITLE
Anyone else want to take over oraganization admin?

### ISSUE THREAD

**Issue by jden** [beerjs/meta#62]
/cc @beerjs/owners @beerjs/organizers 

I've been at this for a while, and think it would be good if anyone else wanted to take up the reins.

Duties are minimal: moderate disputes when they arise (has only happened once), service and enforce the [https://github.com/beerjs/meta#code-of-conduct](code of conduct), and read the issues and pull requests on this repo (creating new repos, small amounts of github org admin / team creation, etc).

So, what say you? Anyone up for it?

**Comment by jordanpapaleo** [comment]
I am down to do it

**Comment by jden** [comment]
Oh, hi everyone, meet @jordanpapaleo, your newest admin :) 
/cc @beerjs/organizers 

:beers:

**Comment by gwmccull** [comment]
All HAIL our new overlord, @jordanpapaleo!  Everyone should come visit us in Truckee, California and have a beer with us.

**Comment by vrivas** [comment]
Thanks for accepting the challenge, @jordanpapaleo!! And also thanks to the
(previous) rest of admins.
Greetings from Spain!

2016-01-30 7:17 GMT+01:00 Garrett McCullough <notifications@github.com>:

> All HAIL our new overlord, @jordanpapaleo
> <https://github.com/jordanpapaleo>! Everyone should come visit us in
> Truckee, California and have a beer with us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beerjs/meta/issues/62#issuecomment-177084854>.
>



-- 
*Victor Manuel Rivas Santos*
