### ISSUE TITLE
How can I get a Sticker?

### ISSUE THREAD

**Issue by webmechanicx** [beerjs/meta#66]

**Comment by jordanpapaleo** [comment]
We do not have a stash of stickers.  Pretty much people order them when them need them.  You can order them individually off of [sticker mule](http://www.stickermule.com/marketplace/5982-beerjs?gclid=Cj0KEQiA6IC2BRDcjPrjm_istoUBEiQASrLz1nsk8BI_U1xQCefUTl5Q1ULaAr0XzgwEqpYG-X0NlxkaAnYE8P8HAQ).  If you need a larger order let me know and we can figure something out.

**Comment by webmechanicx** [comment]
Thanks for letting me know.
