### ISSUE TITLE
Montreal biere.js?

### ISSUE THREAD

**Issue by ml242** [beerjs/meta#67]
Hi Guys,

I just moved up here and am looking to network. Maybe I could push the beer.js project forward instead of starting something new? Open to input, suggestions, criticisms, etc. But this city should have a chapter.

**Comment by jordanpapaleo** [comment]
Hi Matt - 

Sorry for the delay.  This issue must have gotten lost in my email.  I think it would be great to have a Montreal chapter.  Is there anything I can do to help you with this process?

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
I am going to close this.  Please feel free to reopen it if you still need anything at all.

**Comment by ml242** [comment]
Sorry, Jordan. I was away. I am still interested in starting a chapter, is the first requirement to find a space to hang out?

**Comment by jordanpapaleo** [comment]
Not really. everyone kind of has their own flavor. Some of the meetings are just people that go grab beers somewhere and talk tech or whatever.  The one I run we meet in a co-work facility, we have a beer sponsor from a local brewery, and we almost always have someone present some code on a projector.  Its really up to you.  As long as you are working towards growing the JS community where you are, you are doing it right.

So to start a chapter all you have to do is tell me that you want to start one and Ill make you a repo for it.  Take a look at some of the other chapters README.md file and put something up for your group.  The location can totally change overtime.  You may even find a place that will give you a group discount to come to their place after a while if you guys are behaved ;)

Let me know if you have any other questions.

**Comment by ml242** [comment]
Let's do it, I'll get the ball rolling here.

**Comment by jordanpapaleo** [comment]
What would you like your repo to be named?

**Comment by ml242** [comment]
Let's go with 'montreal'

:)

**Comment by jordanpapaleo** [comment]
Welcome to BeerJS.   Here is your new branch repo: https://github.com/beerjs/montreal.  

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.

Step 1:  Create a README.md file.  There is no right or wrong way to do it.  Here is the one I made for exsmple: https://github.com/beerjs/tahoe/blob/master/README.md.  You are more than welcome to take all, any, or none of the info from any chapter's README file.

Step 2: Create an issue for your first meeting then find ways to share it.  You can do this at work, hang a flier, use Facebook, or whatever.

Step 3: Be consistent with your Meetups.  Having one then skipping will not contribute to building momentum for BeerJS: Montreal.  Don't get discouraged if you have super small events.  Still now I will have events with as little 3 people and as much as 20.

Step 4: Join our slack channel

Feel free to reach out as needed.
