### ISSUE TITLE
Add colaborators to BeerJS/SJC

### ISSUE THREAD

**Issue by danilovaz** [beerjs/meta#69]
I found two friends who will help in organizing the event in São José dos Campos, could you add them as collaborators?

Username: @hliberato and @rodrigoagostin
Reponame: beerjs/sjc

**Comment by jordanpapaleo** [comment]
Hi Danilo -

They have been added.  You now have 4 people on your team.

Don't forget to get to join the BeerJS slack channel :)

Thanks,

Jordan

**Comment by danilovaz** [comment]
I will join!

Thanks @jordanpapaleo

**Comment by danilovaz** [comment]
@jordanpapaleo Sorry for reopen this, but I think here is better than create a new issue. Can you remove user fbsobral from admins BeerJS/SJC? He left from our community.

Now I need one more thing :laughing: 

We added 2 women in the organization. In order to make our Meetup BeerJS open to all. You could add these two women as admin BeerJS / SJC repository?

Users are: https://github.com/marondino and https://github.com/DesaSPFC

Thank's.

**Comment by jordanpapaleo** [comment]
Hi!  

No worries at all.

So your current team:

- danilovaz
- hliberato
- rodrigoagostin
- jordanpapaleo

Pending: 

- marondino
- DesaSPFC

Does this look right?

**Comment by danilovaz** [comment]
Yes :laughing: 

Thank's so much!

**Comment by jordanpapaleo** [comment]
Hi.  Sorry for the delay, I was out of town.  

Just have them accept their invitations and you guys should be good to go.

Please close this once you confirmed that you team is where you want it :)

**Comment by danilovaz** [comment]
thank's @jordanpapaleo
