### ISSUE TITLE
Jacksonville Beer JS

### ISSUE THREAD

**Issue by davidfekke** [beerjs/meta#71]
Please fork a repo for Jacksonville.

The only github user I have so far is 'davidfekke'.

**Comment by jordanpapaleo** [comment]
Welcome to BeerJS!   Here is your new branch repo: https://github.com/beerjs/jacksonville

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.

Step 1:  Create a README.md file.  There is no right or wrong way to do it.  Here is the one I made as an example: https://github.com/beerjs/tahoe/blob/master/README.md.  You are more than welcome to take all, any, or none of the info from any chapter's README file.

Step 2: Create an issue for your first meeting then find ways to share it.  You can do this at work, hang a flier, use Facebook, or whatever.

Step 3: Be consistent with your Meetups.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now I will have events with as little 3 people and as much as 20.

Step 4: Join our slack channel

Feel free to reach out as needed.
