### ISSUE TITLE
A couple of useful stuff

### ISSUE THREAD

**Issue by juanbrujo** [beerjs/meta#76]
I made this things to help improve BeerJS Santiago events, they're open-sourced if it helps any other location:

- [BeerJS Pizzas Calculator](https://github.com/juanbrujo/beerjs-pizzas)

- [BeerJS Cleaver Theme](https://github.com/juanbrujo/cleaver-beerjs)

The site is also opensource:

- [BeerJS Santiago theme](https://github.com/juanbrujo/beerjs-santiago)

Maybe add it to a _useful stuff_ directory or .md file

**Comment by jordanpapaleo** [comment]
file added :)
