### ISSUE TITLE
New chapter for Fortaleza, Brazil

### ISSUE THREAD

**Issue by cjpatoilo** [beerjs/meta#78]
Hi everyone, I would like to start a BeerJS chapter for [Fortaleza, Brazil](https://goo.gl/OrhyMV). I am [@cjpatoilo](https://twitter.com/cjpatoilo) on Twitter and I work at Pluralsight as a Software Engineer. I organize the Node User Group meetings in Fortaleza and I have been using Node.js for ~4 years and would like to continue helping others learn with the help of this project.

Thanks guys, it's a great project!

**Comment by jordanpapaleo** [comment]
Awesome and welcome. I will get you setup. What would you like the chapter name to be?

Thanks,

Jordan

Sent from my iPhone

On Jul 23, 2016, at 5:18 AM, CJ Patoilo <notifications@github.com> wrote:

Hi everyone, I would like to start a BeerJS chapter for Fortaleza, Brazil. I am @cjpatoilo on twitter and I work at Pluralsight as a Software Engineer. I organize the Node User Group meetings in Fortaleza and I have been using Node.js for ~4 years and would like to continue helping others learn with the help of this project.

Thanks guys, it's a great project!

**Comment by cjpatoilo** [comment]
Hi @jordanpapaleo, `beerjs/fortaleza`

**Comment by vrivas** [comment]
Hi @cjpatoilo!
It's sounds very well. I'll tell to a good friend from Fortaleza that was studying in Spain a few years ago.
Don't forget to open your own channel in https://beerjs.slack.com
Regards,
Victor

**Comment by cjpatoilo** [comment]
Hi @vrivas 

What great news to know that you know someone in Fortaleza. I hope one day you can know the city, it is amazing.

BTW, in September there will be a great event on JavaScript in Fortaleza. My idea is to link the BeerJS after event.  =)

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/fortaleza

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running.

1:  Create a README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from any chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks.

Jordan
