### ISSUE TITLE
Utrecht edition

### ISSUE THREAD

**Issue by TonD83** [beerjs/meta#81]
@pavadeli and I (@TonD83) would like to start an **Utrecht** beerjs branch. **beerjs/utrecht** would be a wonderful url slug I suppose. Utrecht is a city right in the middle of The Netherlands, by the way. 

While you consider our request, cheers!
![animated-beer-image-0012](https://cloud.githubusercontent.com/assets/18580063/17779202/195fcc42-6567-11e6-903a-b55628a4c065.gif)

**Comment by jordanpapaleo** [comment]
Absolutely.  I was out writing code in Amsterdam last year when I worked for Famo.us.  I love your country and was considering moving to that office full time.  Glad to have you guys apart of BeerJS!

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/utrecht

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/).

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks.

Jordan
