### ISSUE TITLE
BeerJS in Kharkiv, Ukraine

### ISSUE THREAD

**Issue by ghaiklor** [beerjs/meta#84]
Hi there.

I'd like to create BeerJS event in Kharkiv, Ukraine. Could you create repository for this, please?

City name - kharkiv (repository name as well).

Thanks!

**Comment by chicoxyzzy** [comment]
Would love to see Kharkiv in BeerJS organisation!

**Comment by ghaiklor** [comment]
@chicoxyzzy maybe will be faster if we mention administrator of this organization ?

**Comment by vrivas** [comment]
Hi guys!
Give some time to @jordanpapaleo, he uses to be quite busy!
In any case, you can also contact him at papaleowebdev@gmail.com, as I can see at beerjs/meta 
May be @voodootikigod or @cramforce can also help.
Good luck.js

**Comment by jordanpapaleo** [comment]
Thank you @vrivas.

Sorry for the delay but I am sure you all can relate to times when it gets a little busy.

## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/kharkiv

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks.

Jordan

**Comment by jordanpapaleo** [comment]
@chicoxyzzy what team are you requesting to join?

**Comment by chicoxyzzy** [comment]
@jordanpapaleo it's a little bit off-topic here but I'm requesting to join organizers team (I'm BeerJS Moscow organizer since 2015)

**Comment by jordanpapaleo** [comment]
Hi Lets move this offline - 

Send me a quick email please :)


Thanks,

Jordan

papaleowebdev@gmail.com
