### ISSUE TITLE
BeerJS Amsterdam team

### ISSUE THREAD

**Issue by jpwesselink** [beerjs/meta#94]
Aloha, could you add me to the Amsterdam team? Thanks!

**Comment by jordanpapaleo** [comment]
Hoi!

I'll get you setup tomorrow. 

Sent from my smallest computer

On Jan 30, 2017, at 12:19 PM, JP Wesselink <notifications@github.com> wrote:

Aloha, could you add me to the Amsterdam team? Thanks!

**Comment by jordanpapaleo** [comment]
You are on this team

![image](https://cloud.githubusercontent.com/assets/1728807/22482695/fc440b30-e7ae-11e6-911a-2834d8357b38.png)

Is something not working?

Let me know :)

**Comment by jpwesselink** [comment]
Hi, hey thanks. Couldn't find out how I had permissions on this repo, couldn't see who is on that team. Ok lies, I just want to be part of the org so I can show off the beerjs logo on my public profile. There, I said it.

**Comment by jordanpapaleo** [comment]
Sweet!

Let me know if you need anything else. 

Doi 

Sent from my smallest computer

On Jan 31, 2017, at 12:37 PM, JP Wesselink <notifications@github.com> wrote:

Hi, hey thanks. Couldn't find out how I had permissions on this repo, couldn't see who is on that team. Ok lies, I just want to be part of the org so I can show off the beerjs logo on my public profile. There, I said it.

**Comment by jpwesselink** [comment]
Doei! En bedankt!

**Comment by jpwesselink** [comment]
Oh hey, it seems that I have lost my permissions for the Amsterdam repo. Can you check this please?

**Comment by jordanpapaleo** [comment]
Here is what you should be able to do on beerjs/amsterdam:

Team members can read, clone, and push to this repository.

What permission is no longer working?

**Comment by jpwesselink** [comment]
I don't think I am a team member - or - I don't know how I can tell that I am a team member. What I do see is that I can't access the settings of the repository anymore.

**Comment by jordanpapaleo** [comment]
I don't think anyone is supposed to be able to do that.  That is admin access.  I am more than happy to do the administrative actions for you but I also don't want to be an obstacle for you.  Do you think you need that access or is pushing and pulling enough?

**Comment by jordanpapaleo** [comment]
You can also chat me in the slack channel. It will be quicker :)

**Comment by jpwesselink** [comment]
I'll hop on Slack in a bit!

**Comment by jordanpapaleo** [comment]
cool!
