### ISSUE TITLE
Beerjs Resistencia setup

### ISSUE THREAD

**Issue by josefernand** [beerjs/meta#96]
Hi all! We would like to start organizing beerjs meetups in our city Resistencia Argentina.
Admin accounts: josefernand, jonathanpdiaz
Repo name: resistencia
Thanks!

**Comment by jordanpapaleo** [comment]
Hi - 

I will get this up soon :)

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/resistencia

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks,

Jordan

**Comment by josefernand** [comment]
Thanks Jordan! We are excited to have our first local BeerJS. We'll be adding more info soon, and of course you are invited to join us!

**Comment by jordanpapaleo** [comment]
I'd love to join you!  Some day. 

Sent from my smallest computer

On Feb 4, 2017, at 1:46 AM, Jose <notifications@github.com> wrote:

Thanks Jordan! We are excited to have our first local BeerJS. We'll be adding more info soon, and of course you are invited to join us!
