### ISSUE TITLE
BeerJS, Skopje

### ISSUE THREAD

**Issue by DBozhinovski** [beerjs/meta#98]
Hello guys!

Great idea, and I've been thinking about starting one in Skopje, Macedonia (probably at a local coworking space).

Thanks!

**Comment by jordanpapaleo** [comment]
## Welcome to BeerJS!   
### Here is your new branch repo: https://github.com/beerjs/skopje

Make sure you read and adhere to the [Citizen Code of Conduct
](http://citizencodeofconduct.org/)

You have now write access to this repo.  Please create a new issue if you want to add additional contributors to this repository.  Below are some suggestions to help you get you community up and running:

1:  Update your README.md file.  There is no right or wrong way to do it.  Here is the one I made as an [example](https://github.com/beerjs/tahoe/blob/master/README.md).  You are more than welcome to take all, any, or none of the info from **any** chapter's README file.

2: Create an issue for your first meeting then find ways to share it.  You can do this at work, coffee shops, hang a flier, use Facebook, or whatever.

3: Be consistent with your events.  Having one then skipping will not contribute to building momentum for your BeerJS.  Don't get discouraged if you have super small events.  Still now, I will have events with as little 3 people and as much as 20.

4: Submit a pull request for beerjs/meta and add your location to the `locations.geojson` file.

5: Join our [slack channel](https://beerjs-slack-invite.herokuapp.com/) and keep in touch.

Feel free to reach out as needed.

Thanks,

Jordan

**Comment by DBozhinovski** [comment]
@jordanpapaleo Thanks, but I don't seem to have write access to the repo created for Skopje? Username is `DBozhinovski`, should have mentioned that in the initial message I suppose?

**Comment by jordanpapaleo** [comment]
Oh. You should. Let me double check. 

Sent from my smallest computer

On Apr 5, 2017, at 3:58 PM, Darko Bozhinovski <notifications@github.com> wrote:

@jordanpapaleo Thanks, but I don't seem to have write access to the repo created for Skopje? Username is DBozhinovski, should have mentioned that in the initial message I suppose?

**Comment by DBozhinovski** [comment]
![screenshot_20170406_143029](https://cloud.githubusercontent.com/assets/271746/24754239/f73e067c-1ad5-11e7-9d04-faa65a78414c.png)

No luck unfortunately :(

**Comment by jordanpapaleo** [comment]
Slammed last 2 days. I'll get you fixed today. 

Sent from my smallest computer

On Apr 5, 2017, at 3:58 PM, Darko Bozhinovski <notifications@github.com> wrote:

@jordanpapaleo Thanks, but I don't seem to have write access to the repo created for Skopje? Username is DBozhinovski, should have mentioned that in the initial message I suppose?

**Comment by jordanpapaleo** [comment]
<fingers-crossed>It should work now</fingers-crossed>

**Comment by DBozhinovski** [comment]
Cool, works now! Thanks :)
